# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: test building of EasyBuild documentation
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Codespell action
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true

    - name: install mkdocs
      run: |
          pip install -r requirements.txt
          mkdocs --version

    - name: build tutorial
      # can't use --strict due to warnings being produced by mkdocs-redirect plugin
      # because we are re-directing .html pages
      # run: mkdocs build --strict
      run: mkdocs build
